### ISSUE TITLE
GitLab top level tool cannot be an assistant

### ISSUE THREAD

**Issue by cjellick** [gptscript-ai/desktop#215]
The top level gitlab tool at https://github.com/gptscript-ai/tools/blob/main/apis/gitlab/tool.gpt is written as an assistant. Tools in this repo cannot be written that way because it changes the personailty/context of the assistant that is imports them as a tool.

Take a look at this screen shot

![Image](https://github.com/user-attachments/assets/dc4945a6-9df0-4a2c-9f2a-db0cb56d0601)

You can see that the messages coming back to not match how ive described the assistant.

**Comment by cjellick** [comment]
Bill revamp the gitlab tool

**Comment by sangee2004** [comment]
I am able to work with a gitlab tool.

Created an assistant and added gitlab tool using "Add by URL".

Able to chat with this assistant and see the assistant name given in the instruction of the assistant being used.



![Image](https://github.com/user-attachments/assets/7626c334-85eb-41fa-92f8-ee91f33e7c80)


I was able to list projects and then do some queries relating to latest commits , creating/commenting/closing issues in this project.

@cloudnautique  I am not able to list gitlab repos directly. Wanted to confirm that it is expected since in my case I just created 1 project  which i cloned from gptscript repo.

![Image](https://github.com/user-attachments/assets/1e1a57c4-4c63-4df7-bf84-871edbfd2664)

**Comment by cloudnautique** [comment]
In GitLab top levels are projects and repos belong to projects. It doesn't believe it knows enough to answer a question about a repo. 

You can try adding some dynamic instructions:
```
#!sys.echo

When a user asks for Repos without a project reference, list all projects
```
Not sure if this should be in the base tool or not, since it is in the realm of assistant behavior.

**Comment by cjellick** [comment]
i agree - should not be in the tool.

**Comment by sangee2004** [comment]
Adding the dynamic instructions to the assistant , results in listing the project details
<img width="823" alt="Screenshot 2024-08-28 at 4 02 20 PM" src="https://github.com/user-attachments/assets/8be7ec8f-e42c-4721-9d63-91de35e6e2d3">

@cjellick I did some very checks with gitlab like  listing projects and then do some queries relating to latest commits , creating/commenting/closing issues in this project.

Can this issue be closed with these validations?
