### ISSUE TITLE
knowledge tool is not able to work with files that are present in workspace directory.

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/desktop#235]
Electron build from - `731700663eb1eae4d`

Steps to reproduce the problem:
1. Chat with `Tildy`
2. Set workspace to a directory that has files in them say `file1`
3. Use "Add Knowledge" to add  a file say -`file2`
4. When asking questions about information in `file2` , knowledge tool is able to retrieve information successfully from this file.
5. But when asking questions about information in `file1` , knowledge tool is not able to retrieve any information.

**Expected Behavior:**
Knowledge tool should be able to retrieve information from `file1` as well.

**Comment by cjellick** [comment]
@sangee2004 When you say:
> Add "knowledge tool" and add a file say -file2

did you add file2 via "Add Knowledge" or Manage Workspace? 


I think we're going to remove th knowledge tool from the catalog since knowledge is now more of a built-in feature and we've changed how the tool behaves so that it works better in its more deeply integrated form. I just want to understand what you did first

**Comment by sangee2004** [comment]
@cjellick I meant to have it as "Add Knowledge" in step3 instead of  add "knowledge tool" in  the bug description which I will correct.
```
3. Add "knowledge tool" and add a file say -file2
```

But I got confirmation that we will not be supporting the ingestion of files that are present in workspace directory. 

Will close this issue.
