### ISSUE TITLE
When asking queries relating to knowledge files, i have to ask specifically to use knowledge for knowledge tool to be used and citations are not included.

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/desktop#272]
Electron build - `4884a2ba1901`

**Steps to reproduce the problem:**
1. Chat with `Tildy` and add knowledge file using  `Add Knowledge` option.
2. Ask any question relating to the knowledge file
3. There is no tool call made to knowledge and the information i get is not from  knowledge file I added.
4. I have to ask LLM to specifically use knowledge tool for the queries.
5. Also I am not seeing the citations being listed.

I do see the following context present in the stack trace view:
<img width="682" alt="Screenshot 2024-08-23 at 9 54 15 AM" src="https://github.com/user-attachments/assets/3fdfe113-5976-44c7-bacf-6f6f6d9c0195">

**Expected Behavior:**
For queries relating to knowledge files, knowledge tool has to be used and citations should be included in the responses from knowledge.

**Comment by cjellick** [comment]
@sangee2004 i thought this got better and in fact swung far the other way where it would always try knowledge. Am I imagining that or did it actually get better and then regress again?

**Comment by cjellick** [comment]
@sangee2004 when you create a bug like this, can you provide more specific steps to reproduce?

We dont konw what query you asked or what files you used. It would be a guessing game to try to repro.

**Comment by sangee2004** [comment]
@cjellick I definitely see an improvement in knowledge tool being able to use knowledge files without having to ask it to use it explicitly. The behavior I am seeing now is that it does not reliably work always.
I will provide the exact knowledge used when I see reproduce this issue.

**Comment by sangee2004** [comment]
Tested with electron build - `a8d8c5c39b3d5`

Knowledge file used - [MyFeb12.pdf](https://github.com/user-attachments/files/16770341/MyFeb12.pdf)

Question asked - `What can I eat in empty Stomach`
Answer comes from LLM without knowledge tool call.

Asking `What can I eat in empty Stomach. Use Knowledge` , will result in information being fetched from knowledge tool.

**Comment by iwilltry42** [comment]
I did some testing on this

1. I can replicate that "What can I eat in empty Stomach?" doesn't use knowledge, but "What can I eat in empty Stomach according to my docs?" does. Probably because the question is generic enough to be answered from training data.
2. Difference is that I definitely get source references / citations for every query I give it (if it's using knowledge)

Additional findings as I tested this with ChatGPT:

1. It only uses data from the file, if I ask "What can I eat in empty Stomach?" while attaching the file to the chat (i.e. click "add file", then ask the question). If I ask an unrelated question first, then ask "What can I eat in empty Stomach?", it will use training data to answer unless I ask it to refer to my docs.

2. I did it the direct way, and directly asked "What can I eat in empty Stomach?" when attaching the file. That worked. Then I asked "What are some Cruciferous vegetables?" (which could be answered from the doc as well). That "failed" and answered from training data.

@cjellick - I wonder if we want to push it even more in the direction of chiming in everywhere? If we're going all in on https://github.com/gptscript-ai/desktop/issues/326 - this issue will become irrelevant

**Comment by sangee2004** [comment]
@iwilltry42 I can confirm that when when knowledge tool gets used for a query , we always see the citation being returned now. Craig mentioned that this will be changing. 
But wanted to confirm this finding with you.

**Comment by iwilltry42** [comment]
Large changes to how knowledge is integrated: #385

**Comment by sangee2004** [comment]
Tested with latest build -  `a66cd29e`

I am able to work with knowledge file [MyFeb12.pdf](https://github.com/user-attachments/files/16935238/MyFeb12.pdf) and get the information I need without having to ask specifically to use knowledge tool.
