### ISSUE TITLE
Knowledge - Not able to get the desired information from knowledge file.

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/desktop#448]
Electron build - `f8cb3bd`

**Steps to reproduce the problem:**

1. Start a chat with `Tildy`
2. Using "Add Knowledge" add file - 
[Reunion-Under-The-Stars.pdf](https://github.com/user-attachments/files/16901569/Reunion-Under-The-Stars.pdf)
3. Ask - `Who are the main characters in reunion under the star story?`
4. Response returned is incorrect and is not from knowledge.
5. Ask - `What is the main story line of Reunion under the star?`
6. We get the right response from knowledge file.
7. Ask the same question from step 3.
You will get the right response.

https://github.com/user-attachments/assets/3d1ac2b9-918c-43e7-bf0b-79689333c5bd

8. Upload Travel plan document.
9. Ask for da6 travel plan .
10. I get an message stating that we have no access to specific travel plan.
11. When you ask for knowledge tool to be used , then I get the correct response.

<img width="1023" alt="Screenshot 2024-09-05 at 6 09 04 PM" src="https://github.com/user-attachments/assets/7db220ba-74b2-41db-a45f-92b1c1396074">

I am including the Travel plan document use case as well here since I had never had to coax LLM to use knowledge tool when working with this pdf file.

**Comment by iwilltry42** [comment]
Hey :wave: 
I tested this today with desktop ffcc86f and knowledge https://github.com/gptscript-ai/knowledge/releases/tag/v0.4.14-rc.1.
It answered the first two questions about the story perfectly and failed on the travel plan as you pointed out.

Apparently though the two use cases should be unrelated, since in my testing the first part didn't return responses because of wrong scoring and the travel plan queries fail because the QueryRelevancy Input filter decides that the query is not good enough...
I'll work on that. I think we finally need to include some knowledge base metadata for decision making.

**Comment by sangee2004** [comment]
Tested with latest build of desktop which uses `v0.4.14-rc.11` version of knowledge.

This issue is not seen anymore.
