### ISSUE TITLE
Can't tell what assistant I am running

### ISSUE THREAD

**Issue by sheng-liang** [gptscript-ai/desktop#65]
Click explore and select an assistant to run. The assistant starts but I have no indication on the screen what assistant I am running.

![image](https://github.com/user-attachments/assets/5aa46db8-89eb-4fa0-a3ca-f1580b93f481)

**Comment by cjellick** [comment]
We now put the assistant name at the top, but it isnt "pinned", so you lose it once that chat is long. we probably want to "pin" it.

**Comment by sangee2004** [comment]
This issue is also tracked in https://github.com/gptscript-ai/desktop/issues/127#issuecomment-2289984973

**Comment by cjellick** [comment]
@sangee2004 if an issue is tracked in two places, then close one as a dupe. ill close yours as a dupe and leave this one open

**Comment by cjellick** [comment]
We're going to take this a step farther and add some additional info and features to the "pinned" bar. At a high level, we'll have a dropdown to indicate what tools the assistant currently has, a way to indicate if the assistant has been modified from its original state (by adding tools), and a way to effectively "Save As..." the thread as a new assistant

**Comment by cjellick** [comment]
I need to has out the UX of this a bit more, so dont just pick this up without working on it without talking to me about it first.

**Comment by sangee2004** [comment]
Tested with latest electron build from `d3033b74d0f`

Able to see the the name of assistant in the chat view which is `pinned`  at the top of the chat, so that it is visible even when we have a long chat message history and we are at the most recent message (in the bottom of the message list with scroll bar).

We are also presented with the tool list that are available to this thread from the assistant and the dynamic tools that have been added to the thread.

We are also provided with ability to  to delete the dynamically added tools from this list.

![Image](https://github.com/user-attachments/assets/fdf57178-edc5-4cb4-b441-603a22b948c4)

Issues seen when testing this feature are tracked in other issues:
https://github.com/gptscript-ai/desktop/issues/287
https://github.com/gptscript-ai/desktop/issues/289

**Comment by thedadams** [comment]
The icons are not tracked as part of this issue. They are tracked here: https://github.com/gptscript-ai/desktop/issues/242
